spring.application.name=java-sapient-test-harness

logging.level.root=INFO
logging.level.io.sapient=DEBUG

edge-node.loader.base-dir=.

fusion-node.host=localhost
fusion-node.port=5000
fusion-node.id=00000000-0000-0000-0000-000000000000
fusion-node.tls.enabled=false
fusion-node.tls.ca-cert=tls/ca.pem
fusion-node.tls.client-cert=tls/cert.pem
fusion-node.tls.client-key=tls/key.pem
fusion-node.tls.key-algorithm=RSA
